<a href="https://colab.research.google.com/github/RogerHeederer/NLPwithPyTorch_book/blob/main/Tensor_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 1

Create a 2D tensor and then add a dimension of size 1 inserted at the 0th axis

In [1]:
import torch
import numpy as np

In [5]:
a = torch.rand(3,3)
a = a.unsqueeze(0)
print(a)
print(a.shape)

tensor([[[0.7833, 0.0488, 0.4043],
         [0.9611, 0.6269, 0.3857],
         [0.1891, 0.9058, 0.7955]]])
torch.Size([1, 3, 3])


Exercise 2

Remove the extra dimension you just added to the previous tensor.

In [7]:
a = a.squeeze(0)
print(a)
print(a.shape)

tensor([[0.7833, 0.0488, 0.4043],
        [0.9611, 0.6269, 0.3857],
        [0.1891, 0.9058, 0.7955]])
torch.Size([3, 3])


Exercise 3

Create a random of shape 5x3 in the interaval (3,7)

In [11]:
3 + torch.rand(5,3) * 4

tensor([[5.0791, 6.7126, 3.6459],
        [4.6927, 5.2171, 4.9457],
        [4.0624, 4.7904, 6.5831],
        [5.7474, 6.0130, 3.3999],
        [3.4473, 6.5840, 4.0840]])

Exercise 4

Create a tensor with values from a normal distribution (mean=0, std=1)

In [12]:
a = torch.rand(3,3)
a.normal_(mean=0, std=1)

tensor([[-0.1309,  0.2968,  1.5636],
        [-0.3425,  0.8699, -0.5393],
        [ 0.1137, -0.0511,  0.7846]])

Exercise 5

Retrieve the indexes of all the non zero elements in the tensor torch.

In [22]:
a = torch.Tensor([1, 1, 1, 0, 1])
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

In [25]:
torch.nonzero(a).shape

torch.Size([4, 1])

Exercise 6

Create a random tensor of size(3,1) and then horizonally stack 4 copies together

In [30]:
a = torch.rand(3,1)
print(a)

tensor([[0.1262],
        [0.5598],
        [0.3281]])


In [31]:
a.expand(3,4)

tensor([[0.1262, 0.1262, 0.1262, 0.1262],
        [0.5598, 0.5598, 0.5598, 0.5598],
        [0.3281, 0.3281, 0.3281, 0.3281]])

In [38]:
torch.cat([a,a,a,a], dim=1)

tensor([[0.1262, 0.1262, 0.1262, 0.1262],
        [0.5598, 0.5598, 0.5598, 0.5598],
        [0.3281, 0.3281, 0.3281, 0.3281]])

In [34]:
torch.stack([a, a])

tensor([[[0.1262],
         [0.5598],
         [0.3281]],

        [[0.1262],
         [0.5598],
         [0.3281]]])

In [36]:
torch.cat([a, a], dim=0)

tensor([[0.1262],
        [0.5598],
        [0.3281],
        [0.1262],
        [0.5598],
        [0.3281]])

Exercise 7

Return the batch matrix-matrix product of two 3 dimensional matrices

a=torch.rand(3,4,5)

b=torch.rand(3,5,4)

In [40]:
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
print(a)
print(b)

tensor([[[0.4094, 0.9980, 0.4250, 0.1504, 0.4541],
         [0.3102, 0.0474, 0.8093, 0.6131, 0.7571],
         [0.5573, 0.8236, 0.7563, 0.0282, 0.1677],
         [0.7447, 0.8736, 0.7603, 0.8401, 0.7693]],

        [[0.8363, 0.0117, 0.4842, 0.6310, 0.0162],
         [0.2272, 0.8448, 0.5298, 0.5652, 0.9555],
         [0.5576, 0.4516, 0.8807, 0.0804, 0.1214],
         [0.0213, 0.9007, 0.5870, 0.8717, 0.1643]],

        [[0.5676, 0.7819, 0.3115, 0.8554, 0.0466],
         [0.6507, 0.7628, 0.6591, 0.0755, 0.0521],
         [0.3055, 0.4284, 0.4047, 0.5777, 0.4120],
         [0.3152, 0.8385, 0.8218, 0.0790, 0.7710]]])
tensor([[[9.9722e-02, 9.6720e-01, 5.2147e-01, 6.4195e-01],
         [8.5298e-01, 7.5989e-01, 9.9876e-02, 3.8179e-01],
         [6.7433e-01, 8.7082e-05, 9.4989e-01, 8.9259e-01],
         [9.0945e-01, 3.3490e-01, 7.5147e-01, 6.1709e-01],
         [4.5629e-03, 4.5743e-01, 2.1843e-01, 6.6933e-01]],

        [[3.8365e-01, 5.9391e-01, 7.3233e-01, 3.1477e-01],
         [5.4217e-02, 5.47

In [41]:
torch.bmm(a, b).shape

torch.Size([3, 4, 4])

In [42]:
torch.bmm(a,b)

tensor([[[1.3175, 1.4125, 0.9290, 1.4199],
         [1.1782, 0.8878, 1.5614, 1.8247],
         [1.2945, 1.2512, 1.1491, 1.4769],
         [2.0997, 2.0174, 1.9972, 2.5236]],

        [[1.2742, 1.3343, 0.7086, 1.2746],
         [1.6195, 2.0744, 1.3007, 1.9191],
         [1.1168, 1.5480, 0.7067, 1.1957],
         [1.3878, 1.6723, 0.5149, 1.4869]],

        [[1.4844, 1.0048, 1.2077, 1.1472],
         [1.1491, 0.8040, 0.9753, 1.2731],
         [1.2795, 1.0326, 0.8174, 1.1250],
         [1.7775, 1.2752, 1.0923, 1.7114]]])

Exercise 8.

Return the batch matrix-matrix product of a 3D matrix and a 2D matrix (a=torch.rand(3,4,5), b=torch.rand(5,4)).

In [43]:
a = torch.rand(3,4,5)
b = torch.rand(5,4)

In [47]:
b.unsqueeze(dim=1).shape

torch.Size([5, 1, 4])

In [46]:
b.unsqueeze(0).shape

torch.Size([1, 5, 4])

In [48]:
a.size(0)

3

In [49]:
b.size()

torch.Size([5, 4])

In [53]:
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

tensor([[[1.1733, 1.0460, 0.8707, 1.5320],
         [0.9014, 1.1270, 0.8334, 1.4052],
         [1.5287, 1.3811, 1.2136, 2.2142],
         [1.0752, 0.7361, 0.6440, 1.2014]],

        [[1.4028, 0.9577, 1.0136, 1.8335],
         [0.4700, 0.7468, 0.4653, 0.5482],
         [0.7188, 0.8688, 0.8617, 1.2877],
         [0.5956, 0.6783, 0.4670, 0.9704]],

        [[0.6443, 0.7222, 0.5275, 0.8642],
         [1.3420, 1.1216, 0.7918, 1.4022],
         [0.4736, 0.4905, 0.3251, 0.7891],
         [1.1803, 1.1741, 0.8396, 1.6507]]])

In [54]:
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size())).shape

torch.Size([3, 4, 4])